use_frameworks!

target 'ALSPayMent_Example' do
  pod 'ALSPayMent', :path => '../'
  pod 'UMengUShare/Social/WeChat', '6.4.1'
  target 'ALSPayMent_Tests' do
    inherit! :search_paths

#pod 'FBSnapshotTestCase'
  end
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
  end

end
